/**
 * Rebuilds the offline city database from two sources:
 *  - Swedish urban areas (SCB-derived svenska-orter)
 *  - Swedish postal localities (GeoNames postal-code export)
 *
 * Run manually with: npm run update:cities
 */
import https from "node:https";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCB_URL = "https://raw.githubusercontent.com/hej2010/svenska-orter/main/src/svenska-orter.json";
const POSTAL_URL = "https://symerio.github.io/postal-codes-data/data/geonames/SE.txt";

function fetchText(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        fetchText(new URL(res.headers.location, url).href).then(resolve, reject);
        return;
      }
      if (res.statusCode !== 200) {
        reject(new Error(`HTTP ${res.statusCode} från ${url}`));
        return;
      }
      res.setEncoding("utf8");
      let text = "";
      res.on("data", chunk => { text += chunk; });
      res.on("end", () => resolve(text));
    }).on("error", reject);
  });
}

const keyOf = name => name.toLocaleLowerCase("sv-SE").trim();
const cities = new Map();

const scbRows = JSON.parse(await fetchText(SCB_URL));
for (const row of scbRows) {
  if (!row.locality || !Number.isFinite(Number(row.lat)) || !Number.isFinite(Number(row.lon))) continue;
  const name = row.locality.replace(/\s*\(.*?\)\s*/g, " ").trim();
  if (name.length < 2) continue;
  cities.set(keyOf(name), { name, lat: Number(row.lat), lng: Number(row.lon) });
}

// Several postal codes share one post town. Average their coordinates and add
// only names not already represented by the SCB urban-area source.
const postalGroups = new Map();
for (const line of (await fetchText(POSTAL_URL)).split(/\r?\n/)) {
  if (!line.trim()) continue;
  const fields = line.split("\t");
  const name = fields[2]?.trim();
  const lat = Number(fields[9]);
  const lng = Number(fields[10]);
  if (!name || !Number.isFinite(lat) || !Number.isFinite(lng)) continue;
  const key = keyOf(name);
  const group = postalGroups.get(key) || { name, lat: 0, lng: 0, count: 0 };
  group.lat += lat;
  group.lng += lng;
  group.count++;
  postalGroups.set(key, group);
}
for (const [key, group] of postalGroups) {
  if (!cities.has(key)) {
    cities.set(key, {
      name: group.name,
      lat: group.lat / group.count,
      lng: group.lng / group.count,
    });
  }
}

// Resolve ambiguous duplicate place names to the nationally recognized city.
// The upstream locality source currently lets a smaller place overwrite Lund in Skåne.
const coordinateOverrides = [
  { name: "Lund", lat: 55.7047, lng: 13.1910 },
];
for (const city of coordinateOverrides) cities.set(keyOf(city.name), city);

const sorted = [...cities.values()].sort((a, b) => a.name.localeCompare(b.name, "sv-SE"));
const lines = sorted.map(city =>
  `  { name: ${JSON.stringify(city.name)}, lat: ${city.lat.toFixed(4)}, lng: ${city.lng.toFixed(4)} },`
);
const output = `import type { City } from "../types/game";

/**
 * Offline database of Swedish urban areas and postal localities.
 * Generated by scripts/fetch_cities.js.
 */
export const SWEDISH_CITIES: City[] = [
${lines.join("\n")}
];

const normalize = (value: string) => value.toLocaleLowerCase("sv-SE").trim();

export function createCityMap(): Map<string, City> {
  return new Map(SWEDISH_CITIES.map(city => [normalize(city.name), city]));
}

export function searchCities(query: string, usedNames: Set<string>, limit = 10): City[] {
  const q = normalize(query);
  if (!q) return [];
  const startsWith: City[] = [];
  const contains: City[] = [];
  for (const city of SWEDISH_CITIES) {
    const lower = normalize(city.name);
    if (usedNames.has(lower)) continue;
    if (lower.startsWith(q)) startsWith.push(city);
    else if (lower.includes(q)) contains.push(city);
  }
  return [...startsWith, ...contains].slice(0, limit);
}
`;

const outPath = path.join(__dirname, "..", "src", "data", "cities.ts");
fs.writeFileSync(outPath, output, "utf8");
console.log(`Skapade ${sorted.length} unika tätorter och postorter (${postalGroups.size} postorter).`);
