import Peer,{type DataConnection} from "peerjs";

type LobbyEntry={id:string;name:string;connected?:boolean};
type WireState={phase?:string;currentPlayerIndex?:number;placedCities?:unknown[];eliminationOrder?:unknown[]};
type ConnMeta={playerId:string;name:string};
type SharedPhoto={playerId:string;playerName:string;dataUrl:string};
type Msg=Record<string,unknown>;

const installedKey="__ortenPrankPhotoInstalled";
const watched=new WeakSet<object>();
const hostConnections=new Set<DataConnection>();
const metaByConnection=new WeakMap<object,ConnMeta>();
const photos=new Map<string,SharedPhoto>();
let guestConnection:DataConnection|null=null;
let guestIdentity={id:"",name:"Spelare"};
let lobby:LobbyEntry[]=[];
let wireState:WireState|null=null;
let lastTurnKey="";
let runId=0;
let turnTimer:number|null=null;

const objectMsg=(value:unknown):value is Msg=>!!value&&typeof value==="object";
const jpeg=(value:unknown):value is string=>typeof value==="string"&&value.length<=150000&&/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(value);
const sleep=(ms:number)=>new Promise<void>(resolve=>window.setTimeout(resolve,ms));
const token=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;

function styles(){
  if(document.getElementById("orten-prank-style"))return;
  const el=document.createElement("style");el.id="orten-prank-style";el.textContent=`
  .orten-prank-host,.orten-prank-request{position:fixed;right:12px;bottom:12px;z-index:2147482000;width:min(340px,calc(100vw - 24px));padding:14px;border-radius:18px;border:1px solid rgba(255,255,255,.18);background:rgba(6,17,31,.96);box-shadow:0 22px 70px rgba(0,0,0,.5);color:#fff;font:600 14px/1.4 system-ui}.orten-prank-host b,.orten-prank-request b{display:block;font-size:16px}.orten-prank-host p,.orten-prank-request p{margin:5px 0 10px;color:rgba(255,255,255,.76);font-weight:500}.orten-prank-row{display:flex;gap:8px;align-items:center;padding-top:9px;margin-top:9px;border-top:1px solid rgba(255,255,255,.1)}.orten-prank-row span{flex:1}.orten-prank-host button,.orten-prank-request button,.orten-prank-countdown button,.orten-turn-photo button{border:0;border-radius:12px;padding:9px 12px;font:800 13px system-ui;cursor:pointer}.orten-prank-primary{background:#ff4f9a;color:#fff}.orten-prank-secondary{background:rgba(255,255,255,.12);color:#fff}.orten-prank-actions{display:flex;gap:8px}.orten-prank-actions button{flex:1}
  .orten-prank-countdown{position:fixed;inset:0;z-index:2147483000;display:grid;place-items:center;background:rgba(0,0,0,.86);color:#fff;font-family:system-ui}.orten-prank-countdown section{position:relative;width:min(460px,94vw);overflow:hidden;border-radius:24px;background:#071426;border:1px solid rgba(255,255,255,.18)}.orten-prank-countdown video{display:block;width:100%;max-height:72vh;aspect-ratio:3/4;object-fit:cover;transform:scaleX(-1);background:#000}.orten-prank-count{position:absolute;inset:0;display:grid;place-items:center;font-size:clamp(80px,28vw,170px);font-weight:1000;text-shadow:0 7px 28px #000}.orten-prank-note{position:absolute;left:12px;right:12px;top:12px;padding:8px;border-radius:12px;background:rgba(0,0,0,.58);font-size:13px;text-align:center}.orten-prank-cancel{position:absolute;right:12px;bottom:12px;background:rgba(0,0,0,.62);color:#fff}.orten-prank-countdown.flash section:after{content:"";position:absolute;inset:0;background:#fff;animation:opflash .25s ease-out forwards;pointer-events:none}@keyframes opflash{from{opacity:.95}to{opacity:0}}.orten-prank-gotcha{position:absolute;inset:0;display:grid;place-items:center;background:rgba(0,0,0,.55);font-size:clamp(40px,14vw,80px);font-weight:1000;text-align:center}
  .orten-turn-photo{position:fixed;inset:0;z-index:2147482500;display:grid;place-items:center;padding:18px;background:rgba(1,7,14,.72);font-family:system-ui}.orten-turn-photo article{position:relative;width:min(430px,94vw);padding:14px;border-radius:25px;background:#071426;border:1px solid rgba(255,255,255,.18);text-align:center;color:#fff;box-shadow:0 30px 90px rgba(0,0,0,.6)}.orten-turn-photo img{display:block;width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:18px}.orten-turn-photo strong{display:block;margin-top:10px;font-size:25px}.orten-turn-photo span{display:block;color:rgba(255,255,255,.7);font-weight:800}.orten-turn-photo button{position:absolute;right:20px;top:20px;width:36px;height:36px;padding:0;background:rgba(0,0,0,.65);color:#fff;font-size:20px}
  `;document.head.appendChild(el);
}
function remove(id:string){document.getElementById(id)?.remove()}
function send(connection:DataConnection,message:Msg){try{if(connection.open)connection.send(message)}catch{}}

function renderHost(){
  const active=[...hostConnections].filter(c=>c.open);if(!active.length){remove("orten-prank-host");return}styles();let panel=document.getElementById("orten-prank-host");if(!panel){panel=document.createElement("div");panel.id="orten-prank-host";panel.className="orten-prank-host";document.body.appendChild(panel)}panel.replaceChildren();const title=document.createElement("b"),info=document.createElement("p");title.textContent="🎭 PRANKBILD";info.textContent="Du triggar överraskningen. Spelaren väljer själv om kameran får starta.";panel.append(title,info);active.forEach(connection=>{const meta=metaByConnection.get(connection)||{playerId:"",name:"Spelare"},row=document.createElement("div"),label=document.createElement("span"),button=document.createElement("button");row.className="orten-prank-row";label.textContent=meta.name||"Spelare";button.type="button";button.className="orten-prank-primary";button.disabled=!meta.playerId;button.textContent="📸 Trigga";button.onclick=()=>send(connection,{type:"ORTEN_PRANK_REQUEST",playerId:meta.playerId,token:token()});row.append(label,button);panel!.appendChild(row)})
}

function showRequest(requestToken:string){
  if(!guestConnection?.open||document.getElementById("orten-prank-request"))return;styles();const box=document.createElement("div");box.id="orten-prank-request";box.className="orten-prank-request";box.innerHTML=`<b>📸 Spelledaren triggar en prankbild</b><p>Om du trycker <strong>Kör!</strong> startar frontkameran och en synlig fotonedräkning. Du kan avbryta när som helst. En stillbild skickas till rummet och kan visas när det blir din tur.</p><div class="orten-prank-actions"><button class="orten-prank-secondary" data-no>Nej</button><button class="orten-prank-primary" data-yes>Kör!</button></div>`;box.querySelector<HTMLButtonElement>("[data-no]")!.onclick=()=>box.remove();box.querySelector<HTMLButtonElement>("[data-yes]")!.onclick=()=>{box.remove();void startCountdown(requestToken)};document.body.appendChild(box)
}

function flash(box:HTMLElement){box.classList.remove("flash");void box.offsetWidth;box.classList.add("flash")}
function clickSound(){try{const C=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.type="square";o.frequency.setValueAtTime(800,c.currentTime);o.frequency.exponentialRampToValueAtTime(170,c.currentTime+.08);g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.09);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.1);window.setTimeout(()=>void c.close(),180)}catch{}}
function frame(video:HTMLVideoElement){
  if(!video.videoWidth||!video.videoHeight)return"";const side=Math.min(video.videoWidth,video.videoHeight),sx=(video.videoWidth-side)/2,sy=(video.videoHeight-side)/2,attempts:[[number,number],[number,number],[number,number]]=[[320,.56],[260,.46],[210,.36]];for(const [size,quality] of attempts){const canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d");if(!ctx)continue;ctx.translate(size,0);ctx.scale(-1,1);ctx.drawImage(video,sx,sy,side,side,0,0,size,size);const data=canvas.toDataURL("image/jpeg",quality);if(jpeg(data))return data}return""
}

async function startCountdown(requestToken:string){
  if(!guestConnection?.open||!navigator.mediaDevices?.getUserMedia)return;let stream:MediaStream;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:640},height:{ideal:640}},audio:false})}catch{return}const current=++runId;styles();remove("orten-prank-countdown");const wrap=document.createElement("div"),card=document.createElement("section"),video=document.createElement("video"),count=document.createElement("div"),note=document.createElement("div"),cancel=document.createElement("button");wrap.id="orten-prank-countdown";wrap.className="orten-prank-countdown";video.autoplay=true;video.muted=true;video.playsInline=true;video.srcObject=stream;count.className="orten-prank-count";note.className="orten-prank-note";note.textContent="📷 Kameran är aktiv — du kan avbryta";cancel.className="orten-prank-cancel";cancel.textContent="Avbryt";cancel.onclick=()=>{runId++;stream.getTracks().forEach(t=>t.stop());wrap.remove()};card.append(video,count,note,cancel);wrap.appendChild(card);document.body.appendChild(wrap);try{await video.play()}catch{}const step=async(text:string,ms=620)=>{if(current!==runId)return false;count.textContent=text;await sleep(ms);return current===runId};if(!await step("3")||!await step("2")||!await step("1")){stream.getTracks().forEach(t=>t.stop());wrap.remove();return}count.textContent="📸";flash(wrap);clickSound();await sleep(520);if(!await step("−1")||!await step("−2")||!await step("−3")){stream.getTracks().forEach(t=>t.stop());wrap.remove();return}count.textContent="📸";flash(wrap);clickSound();await sleep(80);const dataUrl=frame(video);stream.getTracks().forEach(t=>t.stop());if(dataUrl&&guestConnection?.open)send(guestConnection,{type:"ORTEN_PRANK_PHOTO",playerId:guestIdentity.id,playerName:guestIdentity.name,token:requestToken,dataUrl});const gotcha=document.createElement("div");gotcha.className="orten-prank-gotcha";gotcha.textContent="GOTCHA! 😂";card.appendChild(gotcha);await sleep(900);if(current===runId)wrap.remove()
}

function showTurnPhoto(photo:SharedPhoto){styles();remove("orten-turn-photo");if(turnTimer!==null)window.clearTimeout(turnTimer);const wrap=document.createElement("div"),card=document.createElement("article"),img=document.createElement("img"),name=document.createElement("strong"),caption=document.createElement("span"),close=document.createElement("button");wrap.id="orten-turn-photo";wrap.className="orten-turn-photo";img.src=photo.dataUrl;img.alt=`Spelarbild för ${photo.playerName}`;name.textContent=`${photo.playerName}s tur!`;caption.textContent="📸 GOTCHA";close.textContent="×";close.onclick=()=>{if(turnTimer!==null)window.clearTimeout(turnTimer);turnTimer=null;wrap.remove()};card.append(close,img,name,caption);wrap.appendChild(card);document.body.appendChild(wrap);turnTimer=window.setTimeout(()=>{wrap.remove();turnTimer=null},4500)}
function maybeTurnPhoto(force=false){if(!wireState||wireState.phase!=="playing"||typeof wireState.currentPlayerIndex!=="number")return;const player=lobby[wireState.currentPlayerIndex],photo=player?.id?photos.get(player.id):undefined;if(!photo)return;const serial=(wireState.placedCities?.length||0)+(wireState.eliminationOrder?.length||0),key=`${player.id}:${serial}`;if(!force&&key===lastTurnKey)return;lastTurnKey=key;showTurnPhoto(photo)}
function updateLobby(value:unknown){if(!Array.isArray(value))return;lobby=value.filter(objectMsg).map(p=>({id:String(p.id||""),name:String(p.name||"Spelare"),connected:Boolean(p.connected)}));renderHost();maybeTurnPhoto()}
function updateState(value:unknown){if(!objectMsg(value))return;wireState={phase:typeof value.phase==="string"?value.phase:undefined,currentPlayerIndex:typeof value.currentPlayerIndex==="number"?value.currentPlayerIndex:undefined,placedCities:Array.isArray(value.placedCities)?value.placedCities:[],eliminationOrder:Array.isArray(value.eliminationOrder)?value.eliminationOrder:[]};maybeTurnPhoto()}

function standard(connection:DataConnection,data:unknown,hostSide:boolean,outgoing:boolean){if(!objectMsg(data)||typeof data.type!=="string"||data.type.startsWith("ORTEN_PRANK_"))return;if(data.type==="JOIN"&&!outgoing&&hostSide){const meta=metaByConnection.get(connection);if(meta){meta.playerId=String(data.id||"");meta.name=String(data.name||"Spelare");renderHost()}}if(data.type==="JOIN"&&outgoing&&!hostSide)guestIdentity={id:String(data.id||""),name:String(data.name||"Spelare")};if(data.type==="LOBBY"&&((hostSide&&outgoing)||(!hostSide&&!outgoing)))updateLobby(data.players);if(data.type==="STATE"&&((hostSide&&outgoing)||(!hostSide&&!outgoing)))updateState(data.state)}
function custom(connection:DataConnection,data:unknown,hostSide:boolean){if(!objectMsg(data)||typeof data.type!=="string"||!data.type.startsWith("ORTEN_PRANK_"))return;if(!hostSide&&data.type==="ORTEN_PRANK_REQUEST"&&String(data.playerId||"")===guestIdentity.id)showRequest(String(data.token||token()));else if(hostSide&&data.type==="ORTEN_PRANK_PHOTO"&&jpeg(data.dataUrl)){const meta=metaByConnection.get(connection),claimed=String(data.playerId||"");if(!meta?.playerId||claimed!==meta.playerId)return;const photo={playerId:meta.playerId,playerName:meta.name,dataUrl:data.dataUrl};photos.set(photo.playerId,photo);hostConnections.forEach(c=>send(c,{type:"ORTEN_PRANK_SHARED",...photo}));maybeTurnPhoto(true)}else if(!hostSide&&data.type==="ORTEN_PRANK_SHARED"&&jpeg(data.dataUrl)){const playerId=String(data.playerId||""),playerName=String(data.playerName||"Spelare");if(playerId){photos.set(playerId,{playerId,playerName,dataUrl:data.dataUrl});maybeTurnPhoto(true)}}}

function watch(connection:DataConnection,hostSide:boolean){if(!connection||watched.has(connection))return;watched.add(connection);metaByConnection.set(connection,{playerId:"",name:"Spelare"});if(hostSide){hostConnections.add(connection);renderHost()}else guestConnection=connection;const original=connection.send.bind(connection);(connection as unknown as {send:(data:unknown,...rest:unknown[])=>void}).send=(data:unknown,...rest:unknown[])=>{standard(connection,data,hostSide,true);return (original as unknown as (data:unknown,...rest:unknown[])=>void)(data,...rest)};connection.on("data",data=>{standard(connection,data,hostSide,false);custom(connection,data,hostSide)});const close=()=>{if(hostSide){const meta=metaByConnection.get(connection);if(meta?.playerId)photos.delete(meta.playerId);hostConnections.delete(connection);renderHost()}else if(guestConnection===connection){guestConnection=null;remove("orten-prank-request");remove("orten-prank-countdown");remove("orten-turn-photo");photos.clear();lobby=[];wireState=null;lastTurnKey=""}};connection.on("close",close);connection.on("error",close)}

function install(){const g=globalThis as unknown as Record<string,unknown>;if(g[installedKey])return;g[installedKey]=true;const proto=Peer.prototype as unknown as Record<string,unknown>,connect=proto.connect as (...args:unknown[])=>DataConnection,emit=proto.emit as (...args:unknown[])=>unknown;if(typeof connect==="function")proto.connect=function(this:Peer,...args:unknown[]){const c=connect.apply(this,args);watch(c,false);return c};if(typeof emit==="function")proto.emit=function(this:Peer,event:unknown,...args:unknown[]){if(event==="connection"&&args[0])watch(args[0] as DataConnection,true);return emit.apply(this,[event,...args])}}
install();
